# Generated by Django 2.2.6 on 2019-10-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191023_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_manage', 'Manage Authors'),)},
        ),
    ]
